ENH Add `gpuci_mamba_retry` for mamba support
rapidsai/gpuci-tools pull request #16
Opened 2021-02-18 22:35 UTC by mike-wendt

In prep for `mamba` support, add an explicit `gpuci_mamba_retry` so we can offer an option for using an retrying on `mamba` commands

This way we don't just assume all `conda` calls should be routed to `mamba`

2021-02-18 23:29 UTC, mike-wendt commented
Not sure that `mamba` throws the same errors, just starting with these and will monitor for the necessary changes

2021-02-23 17:03 UTC, raydouglass requested changes

2021-02-23 17:03 UTC, raydouglass commented on tools/gpuci_mamba_retry
> +function runConda {
Should be renamed to `runMamba`

2021-02-23 17:49 UTC, raydouglass approved these changes

2021-02-23 19:34 UTC, merged